### PR TITLE
Added test case to illustrate query case sensitivity.

### PR DESCRIPTION
**Pull request by phillipCouto**
This test case illustrates the query being case sensitive.

### CODE REVIEW

**Comment by 0x6e6562** [comment]
To get this test to pass with the current setup, you'd need to add a tag to the Tweet def:

```
TimeLine string `cql:"timeline"`
```

Without having looked into this deeply, I think the issue is `TimeLine` is camel cased, and the mapping is not yet smart enough to figure this out :-(

**Comment by phillipCouto** [comment]
Well then :) I guess I will be the first to contribute to cqlr :) BTW loving it so far. It makes my code look so clean!

Great work thus far!

**Comment by 0x6e6562** [comment]
I think what you would need to do is at the point when the resolution from CQL column name to reflect field name fields (on both the original case and the initial upcase fallback), you'd need to switch strategies and then introspect all field names and then canonicalize them to a downcased variant. This would allow you to compare downcase with downcase.

**Comment by 0x6e6562** [comment]
Maybe it would be better to downcase everything by default, since this comparison should only be done once when the strategy is compiled.

**Comment by 0x6e6562** [comment]
You might want to check out 984e897 as an approach to this problem. I realized that we already eagerly introspecting the entire struct as part of the compilation phase, so I what I decided to do is to canonicalize every field and column name to lower case and store a map of the cannonicalized name to the field index. This means that we are paying for the introspection only once, which we were already doing anyway.

**Comment by phillipCouto** [comment]
The only problem with that scenario is there are cases when caring can be honoured in Cassandra and that is when a column is referenced in "". So I was going to see if there is a way to detect if the query has the column name referenced in "".

**Comment by 0x6e6562** [comment]
Can you provide an example that causes a test to fail?

**Comment by phillipCouto** [comment]
I updated this PR it doesn't fail with what is in the master branch but it will fail if you parse the column names in lower case. Maybe in this situation if the property of the structure does not have a `cqlr:""` designation than the mapping is forced to lower case. Otherwise the exact case in the cqlr designation is used? I think casing will be rare in cassandra. I know I have never used it.

**Comment by 0x6e6562** [comment]
I'm getting a bit confused .... I think what you're trying to say is that you'd like to add these two test cases to the test case added in 984e897 ?

**Comment by phillipCouto** [comment]
I have updated my test case to further illustrate my point. These test cases are to make sure the column mapping done by cqlr is mapping correctly with respect to casing of column names and structure property names.

**Comment by phillipCouto** [comment]
I know it is rare for someone to have 2 columns with similar names and only the casing differentiating them but if this case is handled correctly I think cqlr will handle 99% of column mapping scenarios correctly.

**Comment by phillipCouto** [comment]
Also I am not saying cqlr has to decipher the column name it could very well be if someone needs case sensitivity mapping they must use the `cqlr:""` on the property that needs the case sensitive mapping. Otherwise all other columns names are lower cased.

**Comment by 0x6e6562** [comment]
Despite the fact that Github appear to have changed their pull request UI, what I've done is to create a branch that inherits from this pull request (see #3). Hence #3 contains the test case that was specified here. The only modification I have made to the test specification in this PR is to add a user defined `cql` tag to the ambiguous `timeLine` column (and indicated in your last comment).

**Comment by 0x6e6562** [comment]
@phillipCouto Let me know if you think #3 contains the change you need. For some reason, the Travis build does not appear to have been triggered by GitHub. Judging by some recent changes in the behavior of the UI, maybe GitHub have rolled out a change?

**Pull request merged**
